### ISSUE TITLE
HEAD requests not supported

### ISSUE THREAD

**Issue by nfusionz** [tetherless-world/whyis#122]
Using npm's wait-on with Whyis fails, with Apache2 giving the following error:
```
[Thu Sep 12 03:35:20.023797 2019] [wsgi:error] [pid 32:tid 139858737280768] [remote 172.22.0.3:55090] [2019-09-12 03:35:20,023] ERROR in app: Exception on / [HEAD]
[Thu Sep 12 03:35:20.023815 2019] [wsgi:error] [pid 32:tid 139858737280768] [remote 172.22.0.3:55090] Traceback (most recent call last):
[Thu Sep 12 03:35:20.023820 2019] [wsgi:error] [pid 32:tid 139858737280768] [remote 172.22.0.3:55090]   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2311, in wsgi_app
[Thu Sep 12 03:35:20.023823 2019] [wsgi:error] [pid 32:tid 139858737280768] [remote 172.22.0.3:55090]     response = self.full_dispatch_request()
[Thu Sep 12 03:35:20.023827 2019] [wsgi:error] [pid 32:tid 139858737280768] [remote 172.22.0.3:55090]   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1835, in full_dispatch_request
[Thu Sep 12 03:35:20.023830 2019] [wsgi:error] [pid 32:tid 139858737280768] [remote 172.22.0.3:55090]     return self.finalize_request(rv)
[Thu Sep 12 03:35:20.023833 2019] [wsgi:error] [pid 32:tid 139858737280768] [remote 172.22.0.3:55090]   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1850, in finalize_request
[Thu Sep 12 03:35:20.023836 2019] [wsgi:error] [pid 32:tid 139858737280768] [remote 172.22.0.3:55090]     response = self.make_response(rv)
[Thu Sep 12 03:35:20.023839 2019] [wsgi:error] [pid 32:tid 139858737280768] [remote 172.22.0.3:55090]   File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1976, in make_response
[Thu Sep 12 03:35:20.023842 2019] [wsgi:error] [pid 32:tid 139858737280768] [remote 172.22.0.3:55090]     'The view function did not return a valid response. The'
[Thu Sep 12 03:35:20.023847 2019] [wsgi:error] [pid 32:tid 139858737280768] [remote 172.22.0.3:55090] TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
[Thu Sep 12 03:35:20.023862 2019] [wsgi:error] [pid 32:tid 139858737280768] [remote 172.22.0.3:55090]
```

`other_vhosts_access.log` shows this:
```
172.22.0.2:80 172.22.0.3 - - [12/Sep/2019:03:35:48 +0000] "HEAD / HTTP/1.1" 500 219 "-" "-"                                                                                                                                                
172.22.0.2:80 172.22.0.3 - - [12/Sep/2019:03:35:48 +0000] "HEAD / HTTP/1.1" 500 219 "-" "-"                                                                                                                                                
172.22.0.2:80 172.22.0.3 - - [12/Sep/2019:03:35:49 +0000] "HEAD / HTTP/1.1" 500 219 "-" "-"                                                                                                                                                
172.22.0.2:80 172.22.0.3 - - [12/Sep/2019:03:35:49 +0000] "HEAD / HTTP/1.1" 500 219 "-" "-"                                                                                                                                                
172.22.0.2:80 172.22.0.3 - - [12/Sep/2019:03:35:48 +0000] "GET / HTTP/1.1" 200 9852 "-" "curl/7.52.1" 
```
The one get request was done manually with curl.

**Comment by jimmccusker** [comment]
What is the use case for this?
