### ISSUE TITLE
load_nanopub regression from recent refactoring

### ISSUE THREAD

**Issue by gordom6** [tetherless-world/whyis#133]
Broke DSA:

```
+ python3 manage.py load -i ../dsa_whyis/ontologies/geosparql_vocab_all_v1_0_1_updated.rdf -f xml
Traceback (most recent call last):
  File "manage.py", line 5, in <module>
    Manager().run()
  File "/usr/local/lib/python3.6/dist-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/usr/local/lib/python3.6/dist-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/usr/local/lib/python3.6/dist-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/apps/whyis/whyis/commands/load_nanopub.py", line 63, in run
    if nanopub_prepare_graph_store_tempdir is not None:
NameError: name 'nanopub_prepare_graph_store_tempdir' is not defined

```

**Comment by jimmccusker** [comment]
This was fixed a few versions ago.
