### ISSUE TITLE
Can't show nanopub details

### ISSUE THREAD

**Issue by hansidm** [tetherless-world/whyis#168]
1. Load some data with manage.py load. Take of note of the generated nanopub uri
2. Try to access `/about?uri=<nanopub_uri>`
3. The following error happens:
```
129.161.134.211 - - [10/Feb/2020 14:59:54] "GET /about?uri=http://purl.org/twc/dsa/pub/NjY1MTY0Ljc5NTU0ODU3MzE HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/apps/whyis/venv/lib/python3.5/site-packages/flask/app.py", line 2328, in __call__
    return self.wsgi_app(environ, start_response)
  File "/apps/whyis/venv/lib/python3.5/site-packages/flask/app.py", line 2314, in wsgi_app
    response = self.handle_exception(e)
  File "/apps/whyis/venv/lib/python3.5/site-packages/flask/app.py", line 1760, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/apps/whyis/venv/lib/python3.5/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/apps/whyis/venv/lib/python3.5/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/apps/whyis/venv/lib/python3.5/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/apps/whyis/venv/lib/python3.5/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/apps/whyis/venv/lib/python3.5/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/apps/whyis/venv/lib/python3.5/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/apps/whyis/venv/lib/python3.5/site-packages/flask_debugtoolbar/__init__.py", line 125, in dispatch_request
    return view_func(**req.view_args)
  File "/apps/whyis/whyis/decorator/conditional_login_required.py", line 16, in decorated_view
    return func(*args, **kwargs)
  File "/apps/whyis/whyis/blueprint/entity/get_entity.py", line 47, in view
    return current_app.render_view(resource)
  File "/apps/whyis/main.py", line 743, in render_view
    return render_template(views[0]['view'].value, **template_args), 200, headers
  File "/apps/whyis/venv/lib/python3.5/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/apps/whyis/venv/lib/python3.5/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/apps/whyis/venv/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/apps/whyis/venv/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/apps/whyis/venv/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/apps/whyis/templates/nanopublication_view.html", line 2, in top-level template code
    {% from "_macros.html" import render_resource_link, render_rdfa_resource_link, get_label, facts_panel, facts_list, summary_panel, content %}
  File "/apps/whyis/templates/base.html", line 11, in top-level template code
    <title>{{ title() }} - {{ config['site_name'] }}</title>
  File "/apps/whyis/venv/lib/python3.5/site-packages/jinja2/runtime.py", line 579, in _invoke
    rv = self._func(*arguments)
  File "/apps/whyis/templates/base.html", line 2, in template
    {% block title %}{% endblock %}
  File "/apps/whyis/templates/nanopublication_view.html", line 4, in block "title"
    {% for contributor in this.graph[this.nanopub.assertion.identifier:ns.dc.contributor] %}
  File "/apps/whyis/venv/lib/python3.5/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'main.Entity object' has no attribute 'nanopub'
```

**Comment by jimmccusker** [comment]
Fixed in #181 .
