### ISSUE TITLE
Issues with celeryd, celery and redis - version mismatch

### ISSUE THREAD

**Issue by hansidm** [tetherless-world/whyis#50]
I'm getting the following celery error when trying to import data using the SETLr agent:
```
[2019-05-29 19:47:12,068: ERROR/ForkPoolWorker-5] Error processing resource http://purl.org/tw/dsa/provenance/tl_2018_us_state_script in nanopub http://purl.org/twc/dsa/pub/8a07b178-824a-$
Traceback (most recent call last):
  File "/apps/whyis/autonomic.py", line 73, in process_graph
    result = self.process_nanopub(i, o, output_nanopub)
  File "/apps/whyis/autonomic.py", line 91, in process_nanopub
    self.process(i, o)
  File "/apps/whyis/autonomic.py", line 467, in process
    resources = setlr._setl(setl_graph)
  File "/apps/whyis/venv/local/lib/python2.7/site-packages/setlr/__init__.py", line 772, in _setl
    action[0](task, resources)
  File "/apps/whyis/venv/local/lib/python2.7/site-packages/setlr/__init__.py", line 358, in create_python_function
    exec(script.value, local_vars, global_vars)
  File "<string>", line 2, in <module>
```

Here is my `pip freeze` output
```
amqp==2.4.2
aniso8601==6.0.0
arrow==0.13.2
asn1crypto==0.24.0
Babel==2.7.0
backports.functools-lru-cache==1.5
bcrypt==3.1.6
beautifulsoup4==4.7.1
bibtexparser==1.1.0
billiard==3.5.0.5
binaryornot==0.4.4
blinker==1.4
celery==4.2.1
certifi==2019.3.9
cffi==1.12.3
chardet==3.0.4
Click==7.0
cookiecutter==1.6.0
coverage==4.5.3
cryptography==2.6.1
Cython==0.29.9
-e git+https://github.com/tetherless-world/DynamicSpectrumAccess.git@3086c4fd9961c21b572024863a9dfae8836ebdbe#egg=Dynamic_Spectrum_Allocation_Knowledge_Graph
enum34==1.1.6
fabric==2.4.0
filedepot==0.6.0
Flask==1.0.3
Flask-Admin==1.5.3
Flask-BabelEx==0.9.3
Flask-DebugToolbar==0.10.1
flask-ld==0.1
Flask-Login==0.3.2
Flask-Mail==0.9.1
Flask-Principal==0.4.0
Flask-RESTful==0.3.7
Flask-Script==2.0.6
Flask-Security==3.0.0
Flask-Testing==0.7.1
Flask-WebTest==0.0.9
Flask-WTF==0.14.2
future==0.17.1
html5lib==1.0.1
idna==2.8
ijson==2.3
invoke==1.2.0
ipaddress==1.0.22
isodate==0.6.0
itsdangerous==1.1.0
javabridge==1.0.18
Jinja2==2.10.1
jinja2-time==0.2.0
keepalive==0.5
kombu==4.5.0
lxml==4.3.3
Markdown==3.1.1
markdown-rdfa==0.1
MarkupSafe==1.1.1
nltk==3.4.1
nose==1.3.7
numpy==1.16.4
pandas==0.24.2
paramiko==2.4.2
passlib==1.7.1
pkg-resources==0.0.0
poyo==0.4.2
pyasn1==0.4.5
pycparser==2.19
PyJWT==1.7.1
PyNaCl==1.3.0
pyOpenSSL==19.0.0
pyparsing==2.4.0
python-dateutil==2.8.0
python-magic==0.4.15
python-slugify==3.0.2
pytidylib==0.3.2
pytz==2019.1
RDFAlchemy==0.3.dev20190529
rdflib==5.0.0.dev0
rdflib-jsonld==0.5.0.dev0
redis==3.2.0
requests==2.22.0
requests-testadapter==0.3.0
sadi==0.5.6
scipy==1.2.1
selenium==3.141.0
setlr==0.2.11
singledispatch==3.4.0.3
six==1.12.0
soupsieve==1.9.1
SPARQLWrapper==1.8.4
speaklater==1.3
text-unidecode==1.2
toposort==1.5
Unidecode==1.0.23
urllib3==1.25.3
vine==1.3.0
virtualenv==16.6.0
waitress==1.3.0
webencodings==0.5.1
WebOb==1.8.5
WebTest==2.0.33
Werkzeug==0.14.1
whichcraft==0.5.2
WTForms==2.2.1
xlrd==1.2.0
```

I did updated `redis` to `3.2.0` as with the required version from Whyis requirements (`<3`) `celeryd` would break with the following error:
```
● celeryd.service - LSB: celery task worker daemon
   Loaded: loaded (/etc/init.d/celeryd; bad; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2019-05-29 19:15:40 UTC; 6s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 3713 ExecStop=/etc/init.d/celeryd stop (code=exited, status=0/SUCCESS)
  Process: 3887 ExecStart=/etc/init.d/celeryd start (code=exited, status=1/FAILURE)

May 29 19:15:40 ubuntu-xenial celeryd[3887]:     'You have {0.__version__}'.format(redis))
May 29 19:15:40 ubuntu-xenial celeryd[3887]: kombu.exceptions.VersionMismatch: Redis transport requires redis-py versions 3.2.0 or later. You have 2.10.6
May 29 19:15:40 ubuntu-xenial celeryd[3887]: celery multi v4.2.0 (windowlicker)
May 29 19:15:40 ubuntu-xenial celeryd[3887]: > Starting nodes...
May 29 19:15:40 ubuntu-xenial celeryd[3887]:         > w1@ubuntu-xenial: * Child terminated with exit code 1
May 29 19:15:40 ubuntu-xenial celeryd[3887]: FAILED
May 29 19:15:40 ubuntu-xenial systemd[1]: celeryd.service: Control process exited, code=exited status=1
May 29 19:15:40 ubuntu-xenial systemd[1]: Failed to start LSB: celery task worker daemon.
May 29 19:15:40 ubuntu-xenial systemd[1]: celeryd.service: Unit entered failed state.
May 29 19:15:40 ubuntu-xenial systemd[1]: celeryd.service: Failed with result 'exit-code'.
```

**Comment by jimmccusker** [comment]
This was solved in the transition to python 3.
